version: '3.8'
services:
  auth-server:
    build:
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  envoy:
    build:
      dockerfile: Dockerfile.envoy
    ports:
      - "10000:10000"
    depends_on:
      - auth-server